### ISSUE TITLE
アクティブセッションリストの表示と挙動が一致してない

### ISSUE THREAD

**Issue by toritoriVR** [imotchi1214/NeosVRHeadlessClientControl#2]
アクティブセッションリストについて、クローズ等でリストから消しても、手動更新しない限りリストには残り続けると思うのですが。
この時、例えば、3列目のセッションをクローズした後に5列目をクローズすると、内部的には3列目が消えて1段づつずれてるようで、表示上だと6列目のセッションがクローズされる気がします。

**Comment by imotchi1214** [comment]
@toritoriVR 

アクティブセッションリストについて、以下のようにセッションを開いている場合に
「セッション２」をクローズ後、「🔁」ボタンをクリックせず、セッション３をクローズした際に、実際はセッション４がクローズされるという問題と認識しました。

```
・セッション１
・セッション２ **＜クローズ クリック＞**
・セッション３
・セッション４
　　↓
・セッション１
・セッション２（クローズ済み、表示上残ったまま）
・セッション３ **＜クローズクリック＞**
・セッション４
　　↓
・セッション１
・セッション２（クローズ済み。表示上残ったまま）
・セッション３（クローズされない）
・セッション４ **（クローズされる）**
```

暫定対処を行い、クローズ後にアクティブセッションリストが更新されるように修正します。
「リスタート」についてはもう少し対応に時間がかかります。

**Comment by imotchi1214** [comment]
以下にて修正版をリリースしました。
https://github.com/imotchi1214/NeosVRHeadlessClientControl/releases/tag/0.4.8266.43126
