### ISSUE TITLE
フレンドタブの更新ボタンを連打するとユーザが二重に表示される

### ISSUE THREAD

**Issue by archivedoldakiram** [imotchi1214/NeosVRHeadlessClientControl#4]
※機微な事象ですが。
「フレンド」タブの更新ボタン（添付画像○枠）を、
取得完了を待たずに2回連続で押下すると、
同じユーザが縦に二人並んだ状態で表示されてしまうようです。

![ex](https://user-images.githubusercontent.com/109776586/192140798-0394c6e3-5f78-4bf1-a53f-ac68036ed1a6.jpg)

**Comment by imotchi1214** [comment]
報告ありがとうございます。
修正を行い、次回アップデート時に反映されます。

**Comment by imotchi1214** [comment]
以下バージョンで修正が反映されました。
https://github.com/imotchi1214/NeosVRHeadlessClientControl/releases/tag/0.5.8350.35623
